version: '2'

volumes:
  files:
  database:

services:
  aurora:
    image: igw/aurora
    build: aurora/
    volumes:
    - files:/app/media
    - files:/app/static
    - ${DORK_SOURCE}/source
    environment:
      DORK_SOURCE_PATH: /source
    ports:
    - 80:80

  database:
    image: postgres:9.5
    volumes:
    - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: nosecret

  rabbitmq:
    image: rabbitmq:3.6
    hostname: rabbitmq
