version: "2"

services:
  aurora:
    build: aurora/
    volumes:
     - file_data:/app/media
     - file_data:/app/static
    depends_on:
      - db
      - aurora_rabbit
    env_file: ./config/password.env
    ports:
      - 80:80

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: aurora
    volumes:
      - db_data:/etc/postgresql
      - db_data:/var/log/postgresql
      - db_data:/var/lib/postgresql
    env_file: ./config/password.env

  aurora_rabbit:
    image: rabbitmq:3.6
    hostname: aurora_rabbit


volumes:
  file_data:
  db_data:

