version: '2'

volumes:
  files:
  database:

services:
  aurora:
    extends:
      file: common.yml
      service: aurora
    links:
    - database
    - rabbitmq

  database:
    extends:
      file: common.yml
      service: database

  rabbitmq:
    extends:
      file: common.yml
      service: rabbitmq

