version: "2"

services:
  aurora:
    build: aurora/
    volumes:
     - file_data:/app/media
     - file_data:/app/static
    depends_on:
      - db
      - aurora_rabbit
    env_file: ./config/password.env
    networks:
      - back-tier
    ports:
      - 8080:80

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: aurora
    volumes:
      - db_data:/etc/postgresql
      - db_data:/var/log/postgresql
      - db_data:/var/lib/postgresql
    env_file: ./config/password.env
    networks:
      - back-tier

  aurora_rabbit:
    image: rabbitmq:3.6
    hostname: aurora_rabbit
    networks:
      - back-tier

volumes:
  file_data:
  db_data:

networks:
  back-tier:
