version: "2"

services:
  aurora:
    build: app/
    links:
      - db
    networks:
      - back-tier

  db:
    image: postgres
    volumes:
      - postgres-data:/etc/postgresql
      - postgres-data:/var/log/postgresql
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: {DB_PASSWORD}
    networks:
      - back-tier

volumes:
  postgres-data:

networks:
  back-tier:
