version: "2"

services:
  aurora:
    extends:
      file: common.yml
      service: aurora
    links:
    - database
    - rabbitmq
    ports:
      - 80:80

  database:
    extends:
      file: common.yml
      service: database

  rabbitmq:
    extends:
      file: common.yml
      service: rabbitmq

volumes:
  file_data:
  db_data:
