version: '2'

volumes:
  files:
  database:

services:
  aurora:
    image: ${DORK_PROJECT}/aurora
    build: aurora/
    volumes:
    - files:/app/media
    - files:/app/static
    environment:
      DORK_SOURCE_PATH: /source
    ports:
    - 80:80
    links:
    - database
    - rabbitmq
    - redis
    labels:
      dork.root: /app/code
      dork.hotcode: ${DORK_HOT_CODE_PATHS}

  database:
    image: postgres:9.5
    volumes:
    - database:/var/lib/postgresql/data/pgdata
    - ./database/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
    environment:
      POSTGRES_DB: aurora
      POSTGRES_PASSWORD: nosecret
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432

  rabbitmq:
    image: rabbitmq:3.6
    hostname: rabbitmq

  redis:
    image: redis:4.0
    ports:
    - 6379
