version: "2"

services:
  aurora:
    build: aurora/
    links:
      - db
    environment:
      VIRTUAL_HOST: aurora.sepal.local
    env_file: ./config/password.env
    networks:
      - back-tier
    ports:
      - 8080:80
  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: aurora
    env_file: ./config/password.env
    networks:
      - back-tier

networks:
  back-tier:
